/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package xprolog {
public class ParserConstants {

  var EOF:int= 0;
  var SINGLE_LINE_COMMENT:int= 6;
  var CUT:int= 7;
  var ADDOP:int= 8;
  var MULOP:int= 9;
  var RELOP:int= 10;
  var NUMBER:int= 11;
  var DIGIT:int= 12;
  var CHAR_LITERAL:int= 13;
  var VAR:int= 14;
  var ATOM:int= 15;
  var ANYCHAR:int= 16;
  var LOCASE:int= 17;
  var HICASE:int= 18;

  var DEFAULT:int= 0;

  var tokenImage:Array= [
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"!\"",
    "<ADDOP>",
    "<MULOP>",
    "<RELOP>",
    "<NUMBER>",
    "<DIGIT>",
    "<CHAR_LITERAL>",
    "<VAR>",
    "<ATOM>",
    "<ANYCHAR>",
    "<LOCASE>",
    "<HICASE>",
    "\":-\"",
    "\".\"",
    "\":=\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"->\"",
    "\";\"",
    "\"[\"",
    "\"]\"",
    "\"|\""
  ];

}
}